import {defineArrayMember, defineField, defineType} from 'sanity'

export const contactFooter = defineType({
  name: 'contactFooter',
  title: 'Contact / Footer',
  type: 'document',
  groups: [
    {name: 'contact', title: 'Contact Section'},
    {name: 'leadMagnet', title: 'Lead Magnet Widget'},
    {name: 'exitIntent', title: 'Exit Intent Modal'},
    {name: 'footer', title: 'Footer'},
  ],
  fields: [
    defineField({
      name: 'heading',
      title: 'Heading',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'email',
      group: 'contact',
    }),
    defineField({
      name: 'phone',
      title: 'Phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'address',
      title: 'Address',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'contactSectionHeading',
      title: 'Contact Section Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactStudioLabel',
      title: 'Studio Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactInquiriesLabel',
      title: 'Inquiries Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactRequestInfoLabel',
      title: 'Request Info Tab Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactBookConsultLabel',
      title: 'Book Consult Tab Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactNameLabel',
      title: 'Name Field Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmailLabel',
      title: 'Email Field Label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactNameValidationMessage',
      title: 'Name Validation Message',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmailValidationMessage',
      title: 'Email Validation Message',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactSubmitText',
      title: 'Submit Button Text',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactSubmittingText',
      title: 'Submitting Button Text',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactSuccessHeading',
      title: 'Success Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactSuccessDescription',
      title: 'Success Description',
      type: 'text',
      rows: 2,
      group: 'contact',
    }),
    defineField({
      name: 'contactCalendlyHeading',
      title: 'Calendly Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactCalendlyDescription',
      title: 'Calendly Description',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'leadMagnetEyebrow',
      title: 'Lead Magnet Eyebrow',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetHeading',
      title: 'Lead Magnet Heading',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetDescription',
      title: 'Lead Magnet Description',
      type: 'text',
      rows: 3,
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetEmailPlaceholder',
      title: 'Lead Magnet Email Placeholder',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetValidationMessage',
      title: 'Lead Magnet Validation Message',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetSubmitText',
      title: 'Lead Magnet Submit Text',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetSubmittingText',
      title: 'Lead Magnet Submitting Text',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetSuccessHeading',
      title: 'Lead Magnet Success Heading',
      type: 'string',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetSuccessDescription',
      title: 'Lead Magnet Success Description',
      type: 'text',
      rows: 2,
      group: 'leadMagnet',
    }),
    defineField({
      name: 'leadMagnetWhatsappUrl',
      title: 'Lead Magnet WhatsApp URL',
      type: 'url',
      group: 'leadMagnet',
    }),
    defineField({
      name: 'exitIntentEyebrow',
      title: 'Exit Intent Eyebrow',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentHeading',
      title: 'Exit Intent Heading',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentDescription',
      title: 'Exit Intent Description',
      type: 'text',
      rows: 3,
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentEmailPlaceholder',
      title: 'Exit Intent Email Placeholder',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentValidationMessage',
      title: 'Exit Intent Validation Message',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentSubmitText',
      title: 'Exit Intent Submit Text',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentSubmittingText',
      title: 'Exit Intent Submitting Text',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentCloseText',
      title: 'Exit Intent Close Text',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentSuccessHeading',
      title: 'Exit Intent Success Heading',
      type: 'string',
      group: 'exitIntent',
    }),
    defineField({
      name: 'exitIntentSuccessDescription',
      title: 'Exit Intent Success Description',
      type: 'text',
      rows: 2,
      group: 'exitIntent',
    }),
    defineField({
      name: 'footerLinks',
      title: 'Footer Links',
      type: 'array',
      group: 'footer',
      of: [defineArrayMember({type: 'socialLink'})],
    }),
    defineField({
      name: 'copyrightText',
      title: 'Copyright Text',
      type: 'string',
      group: 'footer',
    }),
  ],
  preview: {
    prepare: () => ({
      title: 'Contact / Footer',
    }),
  },
})
